-- Tablas principales
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  author text not null,
  rating int not null check (rating between 1 and 5),
  content text,
  featured boolean default false,
  context text check (context in ('home','service','airport','station')),
  slug text,
  created_at timestamp with time zone default now()
);

create table if not exists public.faqs (
  id bigint generated by default as identity primary key,
  context text not null check (context in ('service','airport','station')),
  slug text not null,
  question text not null,
  answer text not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  url text not null,
  alt text,
  position int,
  active boolean default true,
  created_at timestamp with time zone default now()
);

create table if not exists public.services (
  slug text primary key,
  name text not null,
  title text not null,
  description text not null,
  intro text not null,
  keywords text[],
  benefits jsonb
);

create table if not exists public.airports (
  slug text primary key,
  name text not null,
  city text,
  code text,
  intro text not null,
  description text not null,
  keywords text[]
);

create table if not exists public.stations (
  slug text primary key,
  name text not null,
  city text,
  type text check (type in ('tren','bus')),
  intro text not null,
  description text not null,
  keywords text[]
);

-- RLS: lectura pública
alter table public.reviews enable row level security;
alter table public.faqs enable row level security;
alter table public.gallery enable row level security;
alter table public.services enable row level security;
alter table public.airports enable row level security;
alter table public.stations enable row level security;

do $$ begin
  create policy if not exists "public_read_reviews" on public.reviews for select using (true);
  create policy if not exists "public_read_faqs" on public.faqs for select using (true);
  create policy if not exists "public_read_gallery" on public.gallery for select using (true);
  create policy if not exists "public_read_services" on public.services for select using (true);
  create policy if not exists "public_read_airports" on public.airports for select using (true);
  create policy if not exists "public_read_stations" on public.stations for select using (true);
exception when others then null; end $$;

-- Índices útiles
create index if not exists idx_reviews_context_slug on public.reviews (context, slug);
create index if not exists idx_faqs_context_slug on public.faqs (context, slug);
create index if not exists idx_gallery_active_position on public.gallery (active, position);

